#! /bin/bash

#Connection à dattier

ssh -T mano.lemaire.etu@dattier.iutinfo.fr << 'EOF'

#Création et configuration des VMs

VM_LIST=("SAE4db" "SAE4dolibarr" "SAE4save")

for VM in "${VM_LIST[@]}"; do
    if vmiut lister | grep -q "$VM"; then
        vmiut supprimer "$VM"
    fi
    vmiut creer "$VM"
    vmiut demarrer "$VM"
done

IP_SAVE=$(vmiut info SAE4save | grep ip-potentielle1 | cut -d= -f2)
IP_DOLI=$(vmiut info SAE4dolibarr | grep ip-potentielle1 | cut -d= -f2)
IP_DB=$(vmiut info SAE4db | grep ip-potentielle1 | cut -d= -f2)

ssh-copy-id -i .ssh/id_rsa root@IP_SAVE
ssh-copy-id -i .ssh/id_rsa root@IP_DOLI
ssh-copy-id -i .ssh/id_rsa root@IP_DB

ssh user@$IP_DB << 'DB_EOF'

iface enp0s3 inet static
    address 10.42.173.11
    netmask 255.255.255.0
    gateway 10.42.173.1" > /etc/network/interfaces

DB_EOF

ssh user@$IP_DOLI << 'DOLI_EOF'

iface enp0s3 inet static
    address 10.42.173.10
    netmask 255.255.255.0
    gateway 10.42.173.1" > /etc/network/interfaces

DOLI_EOF

ssh user@$IP_SAVE << 'SAVE_EOF'

iface enp0s3 inet static
    address 10.42.173.12
    netmask 255.255.255.0
    gateway 10.42.173.1" > /etc/network/interfaces

SAVE_EOF

EOF
