#! /bin/bash

#Connection à dattier

ssh mano.lemaire.etu@dattier.iutinfo.fr

#Création et configuration des VMs

VM_LIST=("SAE4db" "SAE4dolibarr" "SAE4save")

for VM in "${VM_LIST[@]}"; do
    if vmiut lister | grep -q "$VM"; then
        vmiut supprimer "$VM"
    fi
    vmiut creer "$VM"
    vmiut demarrer "$VM"
done
