#! /bin/bash

."1 - Initialisation des VMs"
."2 - Installation de PostgreSQL"
."3 - Activation du Reverse Proxy : Traefik"
."4 - Configuration de Dolibarr"
."5 - Ajout Client"
."6 - Mise en place des sauvegardes"